# Generated by Django 4.1.6 on 2023-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("titles", models.PositiveIntegerField(default=0)),
                ("top_score", models.CharField(max_length=50)),
                ("fifa_code", models.CharField(max_length=3)),
                ("first_cup", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
