# Generated by Django 4.1.6 on 2023-02-07 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_team_fifa_code_alter_team_titles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="top_score",
            new_name="top_scorer",
        ),
    ]
